image:
  repository: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/frontend
  tag: latest

replicaCount: 1

service:
  type: NodePort
  port: 80
  nodePort: 30080

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "300m"
    memory: "128Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuThreshold: 50
