image:
  repository: REPLACE_IMAGE_REPO
  tag: REPLACE_IMAGE_TAG

replicaCount: 3

service:
  type: NodePort
  port: 80
  nodePort: 30081

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "300m"
    memory: "128Mi"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuThreshold: 50
